services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=bdias
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=tickets
    volumes:
      - tickets_pg_data:/bitnami/postgresql

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - 'tickets_redis_data:/bitnami/redis/data'

volumes:
  tickets_pg_data:
  tickets_redis_data: